export const appPalette = {
  canvas: '#edf1f3',
  canvasSoft: '#f4f7f8',
  surface: '#ffffff',
  ink: '#14202b',
  inkSecondary: '#465866',
  inkMuted: '#687985',
  line: '#d4dde2',
  lineSoft: '#e2e8eb',
  info: '#397083',
  infoSoft: '#eaf3f5',
  success: '#2f6b4f',
  successSoft: '#edf6f1',
  warning: '#9a681f',
  warningSoft: '#fbf5e8',
  danger: '#b54743',
  dangerSoft: '#fbefee',
} as const;

export const appTheme = {
  token: {
    colorPrimary: appPalette.ink,
    colorInfo: appPalette.info,
    colorSuccess: appPalette.success,
    colorWarning: appPalette.warning,
    colorError: appPalette.danger,
    colorText: appPalette.ink,
    colorTextSecondary: appPalette.inkMuted,
    colorBorder: appPalette.line,
    colorBorderSecondary: appPalette.lineSoft,
    colorBgLayout: appPalette.canvas,
    colorBgContainer: appPalette.surface,
    colorFillAlter: appPalette.canvasSoft,
    colorLink: appPalette.info,
    colorLinkHover: '#305f70',
    controlHeight: 40,
    controlHeightSM: 32,
    controlHeightLG: 44,
    borderRadius: 10,
    borderRadiusLG: 18,
    borderRadiusSM: 8,
    fontFamily:
      '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Segoe UI", sans-serif',
    boxShadowSecondary: '0 18px 40px rgba(15, 23, 42, 0.08)',
  },
  components: {
    Button: {
      controlHeight: 40,
      controlHeightSM: 32,
      controlHeightLG: 44,
      borderRadius: 10,
      borderRadiusSM: 8,
      fontWeight: 600,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Card: {
      bodyPadding: 20,
      headerBg: 'transparent',
    },
    Checkbox: {
      borderRadiusSM: 4,
    },
    Input: {
      activeBorderColor: '#b8c0cc',
      hoverBorderColor: '#b8c0cc',
      activeShadow: '0 0 0 3px rgba(57, 112, 131, 0.10)',
    },
    InputNumber: {
      activeBorderColor: '#b8c0cc',
      hoverBorderColor: '#b8c0cc',
      activeShadow: '0 0 0 3px rgba(57, 112, 131, 0.10)',
    },
    Modal: {
      contentBg: appPalette.surface,
      headerBg: 'transparent',
      titleFontSize: 17,
    },
    Pagination: {
      itemActiveBg: appPalette.surface,
    },
    Select: {
      optionSelectedBg: '#eceff3',
      activeBorderColor: '#b8c0cc',
      hoverBorderColor: '#b8c0cc',
      activeOutlineColor: 'rgba(57, 112, 131, 0.10)',
    },
    Switch: {
      colorPrimary: appPalette.success,
      colorPrimaryHover: '#285c44',
    },
    Table: {
      headerBg: appPalette.canvasSoft,
      headerColor: appPalette.inkMuted,
      borderColor: appPalette.lineSoft,
      rowHoverBg: '#fafbfc',
      rowSelectedBg: '#edf5fa',
      rowSelectedHoverBg: '#e4eff6',
    },
    Tabs: {
      itemSelectedColor: appPalette.ink,
      itemHoverColor: appPalette.ink,
      inkBarColor: '#46bfa7',
    },
  },
};
